"""removed person_type

Revision ID: 75135b8ab712
Revises: e0590c842528
Create Date: 2026-07-13 18:48:47.665605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75135b8ab712'
down_revision: Union[str, Sequence[str], None] = 'e0590c842528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'person_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('person_type', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
