"""create initial schema

Revision ID: e0590c842528
Revises: 
Create Date: 2026-07-13 18:20:31.593701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0590c842528'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('document', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('person_type', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("person_type IN ('pf', 'pj')", name='ck_users_person_type'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_document'), 'users', ['document'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type_account', sa.String(length=20), nullable=False),
    sa.Column('number_account', sa.String(length=20), nullable=False),
    sa.Column('agency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'blocked', 'closed')", name='ck_accounts_status'),
    sa.CheckConstraint("type_account IN ('current', 'savings')", name='ck_accounts_type_account'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type_account', name='uq_user_type_account')
    )
    op.create_index(op.f('ix_accounts_number_account'), 'accounts', ['number_account'], unique=True)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('keys_pix',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('type_key', sa.String(length=20), nullable=False),
    sa.Column('value_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_keys_pix_status'),
    sa.CheckConstraint("type_key IN ('cpf', 'email', 'phone', 'random')", name='ck_keys_pix_type_key'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keys_pix_account_id'), 'keys_pix', ['account_id'], unique=False)
    op.create_index(op.f('ix_keys_pix_value_key'), 'keys_pix', ['value_key'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('account_origin_id', sa.UUID(), nullable=True),
    sa.Column('account_destination_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('concluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'finished', 'failed', 'reversed')", name='ck_transactions_status'),
    sa.CheckConstraint("type IN ('transfer_pix', 'deposit', 'withdrawal', 'reversal')", name='ck_transactions_type'),
    sa.CheckConstraint('account_origin_id IS DISTINCT FROM account_destination_id', name='ck_transaction_origin_destination_different'),
    sa.CheckConstraint('account_origin_id IS NOT NULL OR account_destination_id IS NOT NULL', name='ck_transaction_has_origin_or_destination'),
    sa.CheckConstraint('value > 0', name='ck_transactions_value_positive'),
    sa.ForeignKeyConstraint(['account_destination_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['account_origin_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_table('ledgers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('credit', 'debit')", name='ck_ledger_type'),
    sa.CheckConstraint('value > 0', name='ck_ledger_value_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledgers_account_id'), 'ledgers', ['account_id'], unique=False)
    op.create_index(op.f('ix_ledgers_transaction_id'), 'ledgers', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledgers_transaction_id'), table_name='ledgers')
    op.drop_index(op.f('ix_ledgers_account_id'), table_name='ledgers')
    op.drop_table('ledgers')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_keys_pix_value_key'), table_name='keys_pix')
    op.drop_index(op.f('ix_keys_pix_account_id'), table_name='keys_pix')
    op.drop_table('keys_pix')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_number_account'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_document'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
